security:
    providers:
        cas:
            id: App\Security\User\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout
            guard:
                authenticators:
                    - prayno.cas_authenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/college, roles: [ROLE_ADMIN] }
        - { path: ^/election, roles: [ROLE_ADMIN] }
        - { path: ^/procuration, roles: [ROLE_ADMIN] }
        - { path: ^/scrutin, roles: [ROLE_ADMIN] }
        - { path: ^/secteur, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_USER] }